name: Test installs
on:
  - pull_request
  - push

jobs:

  install:
    strategy:
      matrix:
        python-version:
          - 2.7
          - 3.6
          - 3.7
          - 3.8
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py install
      - run: mackup --help

  install-macos-10:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py install
      - run: ls -l /usr/local/bin
      - run: mackup --help

  install-macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py install
      - run: mackup --help
